export enum PRODUCT_ERROR {
  PRODUCT_CANNOT_BE_DELETED = "PRODUCT_CANNOT_BE_DELETED",
  PRODUCT_CANNOT_BE_UPDATED = "PRODUCT_CANNOT_BE_UPDATED",
  PRODUCT_NAME_ALREADY_EXIST = "PRODUCT_NAME_ALREADY_EXIST",
  PRODUCT_NOT_EXIST = "PRODUCT_NOT_EXIST",
}
